data_local: /home/shuyaoli/LLM-Shearing/llm_data/LLM-Shearing/for_prune
data_remote: # If blank, files must be present in data_local
tokenizer_name: meta-llama/Llama-2-7b-hf
max_seq_len: 4096
global_seed: 17


model:
  name: mosaic_llama2_1.3b
  init_device: "cpu" 
  tokenizer_name: ${tokenizer_name}
  d_model: 2048
  n_heads: 16
  n_layers: 24 
  intermediate_size: 5504
  max_seq_len: ${max_seq_len}
  vocab_size: 32000
  init_std: 0.02
  attn_pdrop: 0.0
  resid_pdrop: 0.0
  emb_pdrop: 0.0
  attn_impl: flash
  rms_norm_eps: 1e-5
  l0_module: null
  path: /home/shuyaoli/LLM-Shearing/models/LLaMA-1-3-B-Pruned/state_dict.pt

# Tokenizer
tokenizer:
  type: hftokenizer
  args:
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train_small
    shuffle: true
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
    is_uint16: true
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: eval_merge
    shuffle: false 
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
    is_uint16: true
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: exponential
  gamma: 0.9

optimizer:
  name: decoupled_sgdw
  lr: 1e-4

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 48000ba
eval_interval: 400ba
eval_subset_num_batches: 1000
global_train_batch_size: 256

# System
seed: ${global_seed}
device_eval_batch_size: 8
device_train_microbatch_size: 16
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: DEFAULT
  activation_checkpointing: true
  activation_cpu_offload: false
  verbose: false

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  memory_monitor: {}
  lr_monitor: {}
  data_loading:
    dynamic: true
    update_type: doremi
    proportion: 
    set_names: 
    target_loss: 


loggers:
  wandb: 
    project: pruning
    entity: pruning
    name: ${run_name}
    init_kwargs:
      mode: offline
      dir: wandb_dir

# Checkpoint to local filesystem or remote object store
save_interval: 3200ba
save_folder: /home/shuyaoli/LLM-Shearing/models/pretrained/${run_name}
autoresume: false